export const COUNTRIES_WITH_CURRENCY: { country: string; currency: string }[] = [
  { country: "United States", currency: "USD" },
  { country: "India", currency: "INR" },
  { country: "Germany", currency: "EUR" },
  { country: "United Kingdom", currency: "GBP" },
  { country: "Canada", currency: "CAD" },
  { country: "Australia", currency: "AUD" },
  { country: "Japan", currency: "JPY" },
  { country: "Brazil", currency: "BRL" },
  { country: "France", currency: "EUR" },
  { country: "Netherlands", currency: "EUR" },
  { country: "Singapore", currency: "SGD" },
  { country: "South Korea", currency: "KRW" },
  { country: "Mexico", currency: "MXN" },
  { country: "South Africa", currency: "ZAR" },
  { country: "Nigeria", currency: "NGN" },
  { country: "Sweden", currency: "SEK" },
  { country: "Switzerland", currency: "CHF" },
  { country: "UAE", currency: "AED" },
  { country: "Poland", currency: "PLN" },
  { country: "Argentina", currency: "ARS" },
];

export const CURRENCY_BY_COUNTRY: Record<string, string> = Object.fromEntries(
  COUNTRIES_WITH_CURRENCY.map((c) => [c.country, c.currency])
);

export const JOB_TITLES: string[] = [
  "Software Engineer",
  "Senior Software Engineer",
  "Staff Engineer",
  "Engineering Manager",
  "Product Manager",
  "Senior Product Manager",
  "Data Scientist",
  "Data Engineer",
  "DevOps Engineer",
  "Senior DevOps Engineer",
  "QA Engineer",
  "Senior QA Engineer",
  "UX Designer",
  "Senior UX Designer",
  "Frontend Engineer",
  "Backend Engineer",
  "Mobile Engineer",
  "Machine Learning Engineer",
  "Security Engineer",
  "Technical Lead",
  "Engineering Director",
  "VP of Engineering",
  "CTO",
  "Solutions Architect",
  "Cloud Engineer",
  "Site Reliability Engineer",
  "Database Administrator",
  "Technical Writer",
  "Scrum Master",
  "Business Analyst",
];
